### ISSUE TITLE
ChromeDriver download is not available

### ISSUE THREAD

**Issue by danqa** [chOOnz/xwalk-chromedriver#1]
I tried to download your patched chromedriver file but its states its not available.

**Comment by danqa** [comment]
@chOOnz Any update on this. Would love to get this working if I can.

**Comment by buekera** [comment]
Sorry @danqa for not responding, didn't noticed you posting.

I will reupload the linux version of the custom chromedriver tomorrow when I find some spare time!

**Comment by buekera** [comment]
@danqa I reuploaded the patched chromedriver for linux, have fun!

**Comment by danqa** [comment]
Thank you @chOOnz

**Comment by saravadeo** [comment]
@chOOnz 

I tried to download your patched chromedriver file but its states its not available.

Can you please reupload it?

And one more thing I am not able to find /appium/lib/devices/android/ folder.

Please help me out here

**Comment by buekera** [comment]
@saravadeo I'm not able to compile the newest version of the Chromedriver for linux right now. I'm sorry but you need to do it yourself for now.

The reason you can't find that folder is because you are using an Appium verison above 1.4.16. When using 1.5+ this patch is not working anymore. I myself threw crosswalk out the window to be able to use appium to it's fullest potential.

**Comment by agarwalkartik** [comment]
@chOOnz The patch you mentioned is not available anymore.Could you please re upload it or tell me another place to find it. Thanks a lot.

**Comment by buekera** [comment]
This repository will not be updated anymore, sorry.
